# Generated by Django 5.2.4 on 2025-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineverso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(related_name='filmes', to='cineverso.genero'),
        ),
    ]
