# Generated by Django 5.2.4 on 2025-08-09 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineverso', '0002_remove_filme_genero_filme_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='dt_lançamento',
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('capa', models.URLField()),
                ('dt_lançamento', models.DateField()),
                ('elenco', models.ManyToManyField(related_name='series', to='cineverso.ator')),
                ('genero', models.ManyToManyField(related_name='series', to='cineverso.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cineverso.filme')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cineverso.serie')),
            ],
        ),
    ]
