# Generated by Django 5.2.4 on 2025-08-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineverso', '0003_filme_dt_lançamento_serie_critica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(upload_to='imagens-mateus/'),
        ),
    ]
