# Generated by Django 5.2.4 on 2025-08-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineverso', '0004_alter_filme_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='capa',
            field=models.ImageField(upload_to='imagens-mateus/'),
        ),
    ]
